# generate client keys
---
- set_fact:
    additional_certs_to_revoke: "{{ _additional_certs_to_revoke.stdout_lines | default([]) }}"
    additional_certs_to_add: "{{ _additional_certs_to_add.stdout_lines | default([]) }}"

- name: Create openvpn ovpn file directory
  file:
    path: "{{openvpn_ovpn_dir}}"
    state: directory

