- name: Synchronization
  synchronize:
    mode: pull
    src: /etc/openvpn/keys
    dest: /tmp/ansible
  when: node == "master"


- name: Synchronization for slaves
  synchronize:
    src: /tmp/ansible/keys/
    dest: /etc/openvpn/keys
  when: node == "slave"


    #- copy: src=/tmp/ansible/{{ item }} dest={{ item }}
    #with_items: "{{ files_to_copy.stdout_lines }}"
    #when: node == "slave"
